### ISSUE TITLE
Perl : 5.34 test failures with Inf NaN numbers  on Windows

### ISSUE THREAD

**Issue by jameysiddiqui** [arsv/perl-cross#117]
CCTYPE		= MSVC120

Failed test 359 - sprintf %c stringy NaN undef at t/op/infnan.t line 31
Failed test 360 - stringy NaN sprintf %c fails at t/op/infnan.t line 32
     got ''
expected /(?^:Cannot printf)/
Failed test 363 - chr stringy NaN undef at t/op/infnan.t line 325
Failed test 364 - stringy NaN chr() fails at t/op/infnan.t line 326
     got ''

Please let me know what needs to be done
expected /(?^:Cannot chr)/
Failed test 368 - stringy NaN pack c fails at t/op/infnan.t line 334
     got 'Cannot pack 0 with \'c\' at t/op/infnan.t line 332.\n'
expected /(?^:Cannot pack NaN)/
Failed test 371 - pack C stringy NaN undef at t/op/infnan.t line 332
Failed test 372 - stringy NaN pack C fails at t/op/infnan.t line 334
     got ''
expected /(?^:Cannot pack NaN)/
Failed test 375 - pack s stringy NaN undef at t/op/infnan.t line 332
Failed test 376 - stringy NaN pack s fails at t/op/infnan.t line 334
     got ''

**Comment by arsv** [comment]
What kind of setup is this? Are you to trying to build perl for a Linux target using a Windows build host?

No idea, I can't reproduce it right away, it seems to be either MSVS libc or Windows specific.
Which is really borderline for perl-cross since it's not really meant for anything other than Linux-Linux builds.

If you can, try building perl natively, using mainline Configure, and compare config.sh from that build to the one perl-cross generates. Chances are some printf-related values are off. Or maybe something FP-related. But I think it's probably printf. If so, it should be hinted most likely.

**Comment by jameysiddiqui** [comment]
this is not cross raised another ticket in perl section
https://github.com/Perl/perl5/issues/19010
