### ISSUE TITLE
Building with -Duseshrplib on Android and linking extensions against libperl.so

### ISSUE THREAD

**Issue by fornwall** [arsv/perl-cross#23]
Hi and thanks for the great work with perl-cross!

When building perl with ´-Duseshrplib` on Android the modules (such as `IO.so`) need to link explicitly against `libperl.so`, since transitive dependencies does not work with the Android linker - see e.g. https://rt.perl.org/Public/Bug/Display.html?id=121011.

Is this possible when using perl-cross?

I'm currently hitting problems as the below (from https://github.com/termux/termux-packages/issues/229):

```
Can't load '/data/data/com.termux/files/usr/lib/perl5/5.22.1/arm-linux/auto/IO/IO.so' for module IO:
 dlopen failed: cannot locate symbol "PL_memory_wrap" referenced by "IO.so"... at /data/data/com.ter
mux/files/usr/lib/perl5/5.22.1/XSLoader.pm line 70.
```

**Comment by arsv** [comment]
Sorry for a very late reply. I'm trying to figure it out, and I strongly suspect that --set-osname=android and/or --set-host-osname=android should be enough to make it use android-specific tricks already in perl-5.22.1.

Having osname="android" on Android should be beneficial in any case, here's a patch to auto-detect that: https://github.com/arsv/perl-cross/commit/298b38abfd7bf5e06c9f5ab869e23942cb328372

However, I'm hesitant to force host-osname="android" because that's wrong, miniperl is running on linux and should have osname="linux". There's clearly some code that depends on that "wrong" though.

**Comment by arsv** [comment]
Ok, finally got config variables right so that Android-specific code in MakeMaker gets triggered.
There should be no need to patch anything to get explicit -lperl when building modules. And Errno.pm should build properly now.

Android ld seems to ignore rpath on perl executable, not sure what to do about that yet, but once libperl is in a known location the rest seems to work fine.

If possible, please try building current master branch.
