### ISSUE TITLE
Bad Errno module with perl-cross-1.1

### ISSUE THREAD

**Issue by fperrad** [arsv/perl-cross#28]
when running tests with a `perl-5.24.0` cross-compiled with `perl-cross-1.1`,
there are many errors related to the `Errno` module.

The first one is :
```
run/switches.t .................................................... 1/115
"EACCES" is not exported by the Errno module
"EISDIR" is not exported by the Errno module
Can't continue after import errors at run/switches.t line 124.
# Looks like you planned 115 tests but ran 8.
```

The last one is :
```
../ext/Errno/t/Errno.t ............................................ 1/12 Bailout called.  Further testing stopped:  No errno's are exported
FAILED--Further testing stopped: No errno's are exported
```

**Comment by arsv** [comment]
What kind of configuration causes this? Is it just a buildroot build?
And a wild guess, could you please check sysroot value in config.sh?

No ideas yet, Errno build fine for me, and I can't see what could be causing it.
But it may be something toolchain-dependent.

**Comment by fperrad** [comment]
Yes, it is a Buildroot 2016.08 configuration.
I start with `qemu_arm_vexpress_defconfig` and after I select an external toolchain (Linaro ARM2016.02).

**Comment by arsv** [comment]
Fixed. Package updated again.

The Linaro part turned out to be crucial. Errno.pm relies on cpp not breaking lines unexpectedly, and only notices $sysroot when $gccversion is set (i.e. when the compiler is detected to be GCC by configure). 

Newer gcc must be run with -E -P instead of just -E to produce output Errno would parse reliably, but sometimes just -E is enough. Linaro toolchains needs -E -P but all non-Linaro gccs I have around (5.x and 6.x) are ok with just -E.

And $gccversion, well, Linaro compiler is not just "GCC", it's "Linaro GCC", which resulted in empty $gccversion and Errno skipping sysroot completely.

Side note, non-patched Errno.pm will silently pick host errno values if built with e.g. clang.

**Comment by arsv** [comment]
One more update, I'm setting non-empty gccversion regardless of the detected compiler type and version.
This is insane but empty $gccversion potentially breaks any cross build.

**Comment by fperrad** [comment]
module `Errno` fixed
