### ISSUE TITLE
LDFLAGS being ignored?

### ISSUE THREAD

**Issue by lancethepants** [arsv/perl-cross#37]
Long time user of perl-cross.  I pass some parameters to LDFLAGS when cross-compiling, in particular the location of the dynamic linker and rpath.

https://github.com/lancethepants/tomatoware/blob/master/scripts/base.sh#L957

Starting on version 1.1.0 these are no longer correctly set, making me think LDFLAGS is perhaps ignored.

**Comment by arsv** [comment]
Oh. Yes, 1.1.0 ignores all *FLAGS in the environment. Not exactly intentional and I'm going to fix it.
Until then, a quick fix: instead of setting LDFLAGS="...", pass -Dldflags="..." to configure. And same with CFLAGS.

CXXFLAGS are not used in perl, and I'm pretty sure neither are CPPFLAGS even though 1.0.x did save them to config.sh.
