### ISSUE TITLE
can perl-cross for armv7l-linux be built on macos?

### ISSUE THREAD

**Issue by giuliomoro** [arsv/perl-cross#79]
I see that it uses `readelf` during `configure`, to check the size of some of the types. This makes me think that it is not meant to be built on macos. What's the deal?
Thanks

**Comment by volth** [comment]
To build `perl` for `armv7l-linux` on macos?

Just curious, can `perl` for `x86_64-linux` be built on macos?
If yes, is it cross-compilation too ?

**Comment by arsv** [comment]
The project is written with the assumption that the build system is a GNU/Linux or something sufficiently compatible.

Regarding readelf, that's just the only way of figuring out type sizes that has been implemented. If you've got readelf, configure will use it, otherwise you need to hint relevant values. Check cnf/hints/, or just run configure with -Divsize=... and so on. Check Porting/Glossary for the meaning of values you have to hint.

Alternatively, run the build in a Linux VM of some sort atop of MacOS.

**Comment by giuliomoro** [comment]
ok thanks. I guess I was asking if there were any known limitations on macos besides fixing this step.

**Comment by arsv** [comment]
No idea, sorry. I don't use MacOS myself and I'm not aware of anyone who'd routinely run perl-cross on MacOS.
